### ISSUE TITLE
gaierror: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by mnaghd01** [psychomario/PyPXE#159]
Hi,

I have recently got introduced to PyPXE package and wanted to try it in a Ubuntu 16.04.3 LTS in a Virtual Box VM environment.
After giving the "PyPXE PyPXE successfully initialized and running!" message, I tried to run the other Virtual Machine which is connected via bridged network and is supposed to simulate the client, but as the client is searching, the PyPXE shuts down giving the below message:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "pypxe/dhcp.py", line 364, in listen
    self.dhcp_offer(message)
  File "pypxe/dhcp.py", line 314, in dhcp_offer
    self.sock.sendto(response, (self.broadcast, 68))
gaierror: [Errno -3] Temporary failure in name resolution

Any help would be very much appreciated

**Comment by psychomario** [comment]
It appears that there is something misconfigured in your setup. What have you set your broadcast address to?
