### ISSUE TITLE
HTTP:  error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by marrotte** [psychomario/PyPXE#164]
Transfer completes successfully, just notice this traceback from the debugger:

>2018-05-16 16:55:03,533 [DEBUG] PyPXE.HTTP Recieved message from ('127.0.0.1', 55271)
2018-05-16 16:55:03,535 [DEBUG] PyPXE.HTTP <--BEGIN MESSAGE-->
2018-05-16 16:55:03,536 [DEBUG] PyPXE.HTTP 'GET /nsx/nsx-unified-appliance-2.1.0.0.0.7395503.ova HTTP/1.1\r\nRange: bytes=2183096320-\r\nUser-Agent: Wget/1.18 (darwin16.0.0)\r\nAccept: */*\r\nAccept-Encoding: identity\r\nHost: 127.0.0.1\r\nConnection: Keep-Alive\r\n\r\n'
2018-05-16 16:55:03,536 [DEBUG] PyPXE.HTTP <--END MESSAGE-->
2018-05-16 16:43:55,147 [DEBUG] PyPXE.HTTP Netboot: netboot, Target: nsx/nsx-unified-appliance-2.1.0.0.0.7395503.ova
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "pypxe/http.py", line 98, in handle_request
    connection.send(data)
error: [Errno 32] Broken pipe

File info:

>(venv) :PyPXE marrotte$ ls -hal netboot/nsx/nsx-unified-appliance-2.1.0.0.0.7395503.ova
-rw-r--r--@ 1 marrotte  staff   2.0G May 16 16:20 netboot/nsx/nsx-unified-appliance-2.1.0.0.0.7395503.ova
(venv) :PyPXE marrotte$

**Comment by psychomario** [comment]
Do the checksums before/after download match? This implies a chunk is failing to send.

**Comment by marrotte** [comment]
Yes.  The md5 sum on source and and target(download) match.
