### ISSUE TITLE
Error on Windows 12 server

### ISSUE THREAD

**Issue by bothwellw** [psychomario/PyPXE#165]
Hi
I am trying  PyPXE for the first time on Windows Server 2012R2.

first  i did
**pip install PyPXE**

then i do:
**python -m pype.server and i get:**

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>python -m pypxe.server
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\pypxe\server.py", line 314, in <module>
    main()
  File "C:\Python27\lib\site-packages\pypxe\server.py", line 158, in main
    if os.getuid() != 0:
**AttributeError: 'module' object has no attribute 'getuid'**

please advise if i have missed anything

Thanks
Bothwell

**Comment by psychomario** [comment]
Please see #72. Unfortunately we do not support Windows.
